# Water conflicts in the Colorado River Basin
## Week 2 - Discussion section

## 1. Archive Exploration

This [Water Conflict and Crisis Events in the Colorado River Basin](https://www.sciencebase.gov/catalog/item/63acac09d34e92aad3ca1480) dataset from the U.S. Geological Survey (USGS) contains data collected from 1) water control board and official organization public meetings regarding the Colorado River Basin and 2) relevant article and newspaper reviews. Data collection spans the years 1970-2005, with the goal of better elucidating water insecurity and conflict as they relate to social vulnerability and improved resource management in the Basin area. 

D. V. Holloman, M. K. Hines, and D. K. Zoanni, “Coded Water Conflict and Crisis Events in the Colorado River Basin, Derived from LexisNexis search 2005-2021.” U.S. Geological Survey, 2023. doi: 10.5066/P9X6WR7J. Available: [https://www.sciencebase.gov/catalog/item/63acac09d34e92aad3ca1480](https://www.sciencebase.gov/catalog/item/63acac09d34e92aad3ca1480). [Accessed: Oct. 7, 2026]

## 2. Data Loading

In [1]:
import pandas as pd

# Load data
df = pd.read_csv('data/Colorado_River_Basin_Water_Conflict_Table.csv')

## 3. Preliminary Data Exploration

In [2]:
# See all columns by setting this option
pd.set_option("display.max_columns", None)

In [3]:
# View dimensions of df
df.shape

(268, 48)

In [4]:
# View first 10 rows
df.head(10)

,Event,Search Source,Newspaper,Article Title,Duplicate,Report Date,Report Year,Event Date,Event Day,Event Month,Event Year,Conflict Present,Crisis Present,Basin,HUC6,HUC2,Place,County,County FIPS,State,State FIPS,Urban or Rural,Issue Type,Event Summary,Stakeholders,Intensity Value,Comments,Related Observation Themes,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
0,1,USGS1-50.docx,The Durango Herald (Colorado),Tribes assert water rights on Colorado River B...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Tribal Nations, State Government, Federal Gove...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,3,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
1,2,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Native American tribes assert water rights on ...,False,7-Apr-22,2022.0,NaN,NaN,4.0,2022.0,Y,N,Upper San Juan,140801,14,"Durango, CO",La Plata,8067.0,CO,8,Both,Water rights more generally,Ute Mountain and Southern Ute representatives ...,"Southern Ute Indian Tribe, Ute Mountain Tribe,...",2.0,The article highlights calls for negotiation b...,Lack of tribal representation,0,0,2,7,0,0,0,1,0,0,17,0,0,0,0,0,0,0,0,0
2,3,USGS1-50.docx,The Salt Lake Tribune,'Very positive change.' New Utah law will be a...,False,17-Mar-22,2022.0,NaN,NaN,3.0,2022.0,N,Y,Great Salt Lake,160203,16,Great Salt Lake,NaN,NaN,UT,49,Both,Instream water rights,A bill is proposed in Utah that would expand t...,"State Government, Any Water Rights Holder, Agr...",3.0,The event is the proposal of the bill at the s...,Dishonoring the absent,0,0,1,2,0,0,0,0,0,0,12,0,0,0,1,0,0,0,12,1
3,4,USGS1-50.docx,Casa Grande Dispatch (AZ),Legislation would let an Arizona tribe lease C...,False,11-Dec-21,2021.0,NaN,NaN,12.0,2021.0,N,Y,Lower Colorado,150301,15,Colorado River Indian Reservation,NaN,NaN,NaN,NaN,Rural,Water rights more generally,The Colorado River Indian Tribes Water Resilie...,"Colorado River Indian Tribes, State Government...",3.0,"Event is proposal of the bill, preliminary agr...",NaN,0,0,2,6,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0
4,5,USGS1-50.docx,The Aspen Times (Colorado),Historically excluded from Colorado River poli...,False,19-Dec-21,2021.0,NaN,NaN,11.0,2021.0,Y,Y,Upper San Juan,140801,14,Southern Ute Indian Reservation,NaN,NaN,NaN,NaN,Rural,Intergovernmental issues,State and federal officials say that Tribal Na...,"Sothern Ute Indian Tribe, Ute Mountain Tribe, ...",-1.0,Interaction between tribal nations and state/f...,Lack of tribal representation,0,0,2,6,0,0,0,7,0,0,18,0,0,0,0,0,0,0,0,0
5,6,USGS1-50.docx,The Arizona Republic (Phoenix),Everyone loses if we cannot agree on how we us...,False,22-Apr-17,2017.0,NaN,NaN,4.0,2017.0,Y,Y,Entire Lower Colorado Basin,NaN,15,State of Arizona,NaN,NaN,AZ,4,Both,Intergovernmental issues,Water management agencies are in a legal dispu...,"Water Managers, All Water Users, Conservation ...",2.0,Event is delays in negotiations between state/...,NaN,0,0,10,11,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
6,7,USGS1-50.docx,Arizona Daily Star (Tucson),Long-term solutions are needed to keep Colorad...,False,15-Jun-18,2018.0,NaN,NaN,6.0,2018.0,N,Y,Entire Colorado River Basin,NaN,"14, 15",Entire Colorado River Basin,NaN,NaN,NaN,NaN,Both,Drought,In light of historically low water levels in L...,"State Government, Federal Government, Water Ma...",2.0,"Event is calls for negotiation, which was met ...",Lack of tribal representation,0,0,2,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,8,USGS1-50.docx,"Navajo Times (Window Rock, Arizona)","Colorado River, stolen by law; Indigenous nati...",False,17-Mar-22,2022.0,NaN,NaN,3.0,2022.0,Y,Y,Entire Colorado River Basin,NaN,"14, 15",Entire Colorado River Basin,NaN,NaN,NaN,NaN,Both,Intergovernmental issues,"Amidst ongoing drought, the Colorado River Ind...","Colorado River Indian Tribes, State Government...",2.0,Although the article focuses quite a bit on hi...,NaN,0,0,0,4,0,0,0,6,0,0,15,0,0,0,0,0,0,0,0,0
8,9,USGS1-50.docx,The Arizona Republic (Phoenix),Tribes seek a greater role in managing Colorad...,False,18-Dec-21,2021.0,"December 14-16, 2021",NaN,12.0,2021.0,Y,Y,Entire Colorado River Basin,NaN,"14, 15",All of Colorado River Basin,NaN,NaN,NaN,NaN,Both,Water rights more generally,Tribes from across the CRB joined the Colorado...,"Ten Tribes Partnership, State Government, Cons...",2.0,The significant efforts of inclusion and real ...,NaN,0,0,1,3,0,0,0,2,0,0,7,0,0,0,0,0,0,0,0,0
9,10,USGS1-50.docx,"Journal, The (Cortez, Dolores, Mancos, CO)",Colorado's water guardians agree on one thing:...,False,29-Jan-21,2021.0,"January 25 - 26, 2021",NaN,1.0,2021.0,Y,Y,Entire Colorado River Basin,NaN,"14, 15",All of Colorado River Basin,NaN,NaN,NaN,NaN,Both,Water transfers,Water managers and others discussed at the CWC...,"State Government, Federal Government, Private ...",-1.0,intensity of -1 based on disagreement on how t...,Positive state-board collaboration,0,0,3,6,1,0,0,0,0,0,7,0,0,0,0,0,0,0,0,0

In [5]:
# See number of unique values per column
df.nunique()

Event                                           268
Search Source                                     6
Newspaper                                        45
Article Title                                   267
Duplicate                                         2
Report Date                                     235
Report Year                                      18
Event Date                                       52
Event Day                                        12
Event Month                                      12
Event Year                                       21
Conflict Present                                  2
Crisis Present                                    2
Basin                                            25
HUC6                                             22
HUC2                                              7
Place                                           135
County                                            3
County FIPS                                       3
State                                            23
State FIPS                                       19
Urban or Rural                                    6
Issue Type                                       19
Event Summary                                   253
Stakeholders                                    199
Intensity Value                                  10
Comments                                        184
Related Observation Themes                       21
Article Text Search - water quality              10
Article Text Search - invasive species            2
Article Text Search - conservation               15
Article Text Search - drought                    19
Article Text Search - flood                      10
Article Text Search - ground water depletion      1
Article Text Search - depletion                   2
Article Text Search - infrastructure              9
Article Text Search - fish passage                1
Article Text Search - instream water rights       1
Article Text Search - water rights               17
Article Text Search - intergovernmental           2
Article Text Search - water transfers             2
Article Text Search - navigation                  2
Article Text Search - fish                        8
Article Text Search - invasive                    3
Article Text Search - diversion                   6
Article Text Search - water diversion             2
Article Text Search - instream                    5
Article Text Search - aquatic                     5
dtype: int64

In [6]:
# View column names, types, missing data counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 48 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Event                                         268 non-null    int64
 1   Search Source                                 268 non-null    object
 2   Newspaper                                     268 non-null    object
 3   Article Title                                 268 non-null    object
 4   Duplicate                                     267 non-null    object
 5   Report Date                                   267 non-null    object
 6   Report Year                                   265 non-null    float64
 7   Event Date                                    248 non-null    object
 8   Event Day                                     18 non-null     float64
 9   Event Month                                   212 non-null    float64
 10  Event Year                                    257 non-null    float64
 11  Conflict Present                              252 non-null    object
 12  Crisis Present                                254 non-null    object
 13  Basin                                         250 non-null    object
 14  HUC6                                          110 non-null    object
 15  HUC2                                          250 non-null    object
 16  Place                                         254 non-null    object
 17  County                                        8 non-null      object
 18  County FIPS                                   8 non-null      float64
 19  State                                         178 non-null    object
 20  State FIPS                                    178 non-null    object
 21  Urban or Rural                                254 non-null    object
 22  Issue Type                                    255 non-null    object
 23  Event Summary                                 256 non-null    object
 24  Stakeholders                                  255 non-null    object
 25  Intensity Value                               255 non-null    float64
 26  Comments                                      190 non-null    object
 27  Related Observation Themes                    86 non-null     object
 28  Article Text Search - water quality           268 non-null    int64
 29  Article Text Search - invasive species        268 non-null    int64
 30  Article Text Search - conservation            268 non-null    int64
 31  Article Text Search - drought                 268 non-null    int64
 32  Article Text Search - flood                   268 non-null    int64
 33  Article Text Search - ground water depletion  268 non-null    int64
 34  Article Text Search - depletion               268 non-null    int64
 35  Article Text Search - infrastructure          268 non-null    int64
 36  Article Text Search - fish passage            268 non-null    int64
 37  Article Text Search - instream water rights   268 non-null    int64
 38  Article Text Search - water rights            268 non-null    int64
 39  Article Text Search - intergovernmental       268 non-null    int64
 40  Article Text Search - water transfers         268 non-null    int64
 41  Article Text Search - navigation              268 non-null    int64
 42  Article Text Search - fish                    268 non-null    int64
 43  Article Text Search - invasive                268 non-null    int64
 44  Article Text Search - diversion               268 non-null    int64
 45  Article Text Search - water diversion         268 non-null    int64
 46  Article Text Search - instream                268 non-null    int64
 47  Article Text Search - aquatic                 268 non-null    int64
dtypes: float64(6), int64(21), object(21)
memory usage: 100.6+ KB

In [7]:
# View summary statistics for quanititative variables
df.describe()

,Event,Report Year,Event Day,Event Month,Event Year,County FIPS,Intensity Value,Article Text Search - water quality,Article Text Search - invasive species,Article Text Search - conservation,Article Text Search - drought,Article Text Search - flood,Article Text Search - ground water depletion,Article Text Search - depletion,Article Text Search - infrastructure,Article Text Search - fish passage,Article Text Search - instream water rights,Article Text Search - water rights,Article Text Search - intergovernmental,Article Text Search - water transfers,Article Text Search - navigation,Article Text Search - fish,Article Text Search - invasive,Article Text Search - diversion,Article Text Search - water diversion,Article Text Search - instream,Article Text Search - aquatic
count,268.000000,265.000000,18.000000,212.000000,257.000000,8.000000,255.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.0,268.000000,268.000000,268.0,268.0,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000
mean,134.500000,2017.449057,18.444444,6.259434,2016.591440,11170.500000,0.219608,0.671642,0.014925,2.007463,4.600746,0.432836,0.0,0.011194,0.555970,0.0,0.0,3.134328,0.003731,0.022388,0.007463,0.410448,0.033582,0.182836,0.011194,0.089552,0.093284
std,77.509139,4.314160,6.887518,3.679539,10.346365,15437.657326,1.995765,1.472729,0.121481,2.633681,4.006680,2.418554,0.0,0.105405,1.281035,0.0,0.0,3.456072,0.061085,0.148219,0.086225,1.109798,0.200166,0.734493,0.105405,0.860822,0.632064
min,1.000000,2005.000000,4.000000,1.000000,1900.000000,4027.000000,-4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,67.750000,2015.000000,13.250000,3.000000,2015.000000,4027.000000,-1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,134.500000,2019.000000,19.000000,5.000000,2019.000000,6047.000000,0.000000,0.000000,0.000000,1.000000,4.500000,0.000000,0.0,0.000000,0.000000,0.0,0.0,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,201.250000,2021.000000,20.000000,9.000000,2021.000000,8067.000000,1.500000,1.000000,0.000000,3.000000,7.000000,0.000000,0.0,0.000000,1.000000,0.0,0.0,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,268.000000,2022.000000,31.000000,12.000000,2023.000000,49055.000000,5.000000,10.000000,1.000000,15.000000,26.000000,31.000000,0.0,1.000000,9.000000,0.0,0.0,18.000000,1.000000,1.000000,1.000000,8.000000,2.000000,7.000000,1.000000,12.000000,9.000000

## 4.